[package]
name = "network-audio-input-adapter"
version = "0.1.0"
authors = ["luyi <luyi@newtranx.com>"]
edition = "2018"

[dependencies]
hyper = "0.12"
futures = "*"
cpal = "0.9"
log = "0.4"
env_logger = "0.6"
